// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://igmhirzlwkpbzwjjdgxh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlnbWhpcnpsd2twYnp3ampkZ3hoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg1MjMxMDcsImV4cCI6MjA3NDA5OTEwN30.OCEdhuQBBkLQa72hOmxC9aUvafHlgac5WJ_aV7JWw5c";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});